### PR TITLE
Qt6

### PR DESCRIPTION
**Pull request by arafune**
Work around a PyQ6.

### CODE REVIEW

**Comment by chstan** [comment]
Hi @arafune,

If you're interested in contributing your PyQt6 update I think it would be welcome. That would be a breaking change so it would be best to update the version to 4.0.0 and add yourself to the contributors list.

Best,
Conrad

**Comment by arafune** [comment]
Hi Conrad, 
Thanks for reply. 

I'm a Mac user and the current Macintosh is based on M1 chip not intel one. On this situation, pyqt5 does not work (at least in my test).   So I have tried to update.  

In my system f.S.show() and ktool(f) work well with pyqt6. 
The changes are essentially about the Enum treatment.
According to the web site (https://www.pythonguis.com/faq/pyqt5-vs-pyqt6/):
The good news is that the change is backwards compatible: the fully-qualified names also work in PyQt5. So you can make the changes in your PyQt5 code before beginning the upgrade progress.

So I think the current contribution may be applied with a snippet like
try:
    from PyQt import QtWidgets
except ModuleNotFoundError:
    from PyQt import QtWidgets

BTY, show_band_tool does not work at all on my system.  Do you have any ideas?

**Comment by sixthfingers** [comment]
Hi @arafune ,

If you can see the pyqt5 icon in the 'Mac tray' but no the GUI window, I think those code would help you:
```
import os
os.environ['QT_MAC_WANTS_LAYER'] = '1'
```
More details:
https://bugreports.qt.io/browse/QTBUG-87014

This solution really work on my Mac mini (M1). You can try the following codes:
```
import os
os.environ['QT_MAC_WANTS_LAYER'] = '1'
import arpes.all as aps
f = aps.load_example_data().spectrum
f.S.show()
```

**Comment by arafune** [comment]
Hi@sixthfingers ,
Thank you for your good information. It works on my system, too.

**Comment by chstan** [comment]
@arafune Do you have details on the band tool error (if one is given?). I'll admit I mostly do curve fitting in Jupyter iteratively (plotting a selection of the "worst" results by MSE and iterating) so I don't use the band tool much these days.

If you're referring to the old Bokeh one I would instead advocate the following general plan for curve fitting:

1. Use data.X.first_exceeding to find approximate band locations. This function sweeps from one edge of the spectrum along a specified direction until the first pixel exceeding some threshold (you can define relative to the max in that sweep) is exceeded. You can think of it as laying a blanket down on your data and it settles near the band.
2. Get closer to band maximum with data.X.max_in_window which takes the argmax in a user defined window. You can use this to approximately snap to the band location
3. Use the prior data as an array parameter to your curve fit with the broadcast fitting.

I've done very very complicated curve fits (hundreds with several bands) this way very quickly.

Since this is fundamentally a separate issue you can open some other issue/pull for the band tool question.

**Comment by chstan** [comment]
@sixthfingers Good to see you again! Thanks also for the Mac expertise. I'm on Windows these days (LabView, Inventor) so I can't easily comment on those issues.

Since it sounds like an environment variable provides a fix, we can just add the change in `arpes/config.py`: it shouldn't affect other platforms.

**Comment by chstan** [comment]
@arafune It looks like the original branch was deleted here. If you open a (new) pull request we can merge your code. Please also make a change to add yourself to the CONTRIBUTORS file.

Best,
Conrad

**Pull request closed without merging**
